In [ ]:
# import csv file to colab
from google.colab import files
upload = files.upload()

Saving winequality-red (1).csv to winequality-red (1).csv


In [ ]:
#  naive_bayes
import pandas as pd
from sklearn.naive_bayes import GaussianNB
from sklearn import metrics
# xay dung du lieu
wine = pd.read_csv("winequality-red (1).csv", sep=";")
x = wine.drop('quality', axis=1)
y = wine["quality"].values
# xay dung mo hinh
model = GaussianNB()
model.fit(x,y)
print(model)
# ung dung mo hinh
kq = model.predict(x)
# hien thi ket qua danh gia
print(kq)
print(metrics.confusion_matrix(y,kq))
print(metrics.classification_report(y,kq))

GaussianNB(priors=None, var_smoothing=1e-09)
[5 5 5 ... 6 5 6]
[[  3   2   4   1   0   0]
 [  2   8  28  13   1   1]
 [  4  26 456 170  25   0]
 [  0  21 180 324 108   5]
 [  0   1  12  74 110   2]
 [  0   0   0   5  11   2]]
              precision    recall  f1-score   support

           3       0.33      0.30      0.32        10
           4       0.14      0.15      0.14        53
           5       0.67      0.67      0.67       681
           6       0.55      0.51      0.53       638
           7       0.43      0.55      0.48       199
           8       0.20      0.11      0.14        18

    accuracy                           0.56      1599
   macro avg       0.39      0.38      0.38      1599
weighted avg       0.57      0.56      0.57      1599



In [ ]:
# k-means
import pandas as pd
from sklearn.cluster import KMeans
from sklearn import metrics
# xay dung du lieu
wine = pd.read_csv("winequality-red (1).csv", sep=";")
x = wine.drop('quality', axis=1)
y = wine["quality"].values
# xay dung mo hinh
model = tree.DecisionTreeClassifier()
model.fit(x,y)
print(model)
# ung dung mo hinh
kq = model.predict(x)
# hien thi ket qua danh gia
print(kq)
print(metrics.confusion_matrix(y,kq))
print(metrics.classification_report(y,kq))

FileNotFoundError: ignored

In [ ]:
import numpy as np # thư viện tính toán toán học
import matplotlib.pyplot as plt # visualize data sử dụng đồ thị
from scipy.spatial.distance import cdist
means = [[2, 2], [9, 2], [4, 9]]
cov = [[2, 0], [0, 2]]
n_samples = 500
n_cluster = 3
X0 = np.random.multivariate_normal(means[0], cov, n_samples)
X1 = np.random.multivariate_normal(means[1], cov, n_samples)
X2 = np.random.multivariate_normal(means[2], cov, n_samples)
X = np.concatenate((X0, X1, X2), axis = 0)

In [ ]:
# cay quyet dinh, tree
import pandas as pd
from sklearn import tree
from sklearn import metrics
# xay dung du lieu
wine = pd.read_csv("winequality-red (1).csv", sep=";")
x = wine.drop('quality', axis=1)
y = wine["quality"].values
# xay dung mo hinh
model = tree.DecisionTreeClassifier()
model.fit(x,y)
print(model)
# ung dung mo hinh
kq = model.predict(x)
# hien thi ket qua danh gia
print(kq)
print(metrics.confusion_matrix(y,kq))
print(metrics.classification_report(y,kq))

DecisionTreeClassifier(ccp_alpha=0.0, class_weight=None, criterion='gini',
                       max_depth=None, max_features=None, max_leaf_nodes=None,
                       min_impurity_decrease=0.0, min_impurity_split=None,
                       min_samples_leaf=1, min_samples_split=2,
                       min_weight_fraction_leaf=0.0, presort='deprecated',
                       random_state=None, splitter='best')
[5 5 5 ... 6 5 6]
[[ 10   0   0   0   0   0]
 [  0  53   0   0   0   0]
 [  0   0 681   0   0   0]
 [  0   0   0 638   0   0]
 [  0   0   0   0 199   0]
 [  0   0   0   0   0  18]]
              precision    recall  f1-score   support

           3       1.00      1.00      1.00        10
           4       1.00      1.00      1.00        53
           5       1.00      1.00      1.00       681
           6       1.00      1.00      1.00       638
           7       1.00      1.00      1.00       199
           8       1.00      1.00      1.00        18

    accuracy

In [ ]:
# import csv file to colab
from google.colab import files
upload = files.upload()

Saving iris.csv to iris (1).csv


In [ ]:
# cay quyet dinh, tree
import pandas as pd
from sklearn import tree
from sklearn import metrics
# xay dung du lieu
iris = pd.read_csv("iris (1).csv")
print(iris)
x = iris.drop("Name", axis=1)
y = iris["Name"].values
# xay dung mo hinh
model = tree.DecisionTreeClassifier()
model.fit(x,y)
print(model)
# ung dung mo hinh
kq = model.predict(x)
# hien thi ket qua danh gia
print(kq)
print(metrics.confusion_matrix(y,kq))
print(metrics.classification_report(y,kq))

     SepalLength  SepalWidth  PetalLength  PetalWidth            Name
0            5.1         3.5          1.4         0.2     Iris-setosa
1            4.9         3.0          1.4         0.2     Iris-setosa
2            4.7         3.2          1.3         0.2     Iris-setosa
3            4.6         3.1          1.5         0.2     Iris-setosa
4            5.0         3.6          1.4         0.2     Iris-setosa
..           ...         ...          ...         ...             ...
145          6.7         3.0          5.2         2.3  Iris-virginica
146          6.3         2.5          5.0         1.9  Iris-virginica
147          6.5         3.0          5.2         2.0  Iris-virginica
148          6.2         3.4          5.4         2.3  Iris-virginica
149          5.9         3.0          5.1         1.8  Iris-virginica

[150 rows x 5 columns]
DecisionTreeClassifier(ccp_alpha=0.0, class_weight=None, criterion='gini',
                       max_depth=None, max_features=None, max

In [ ]:
import pandas as pd
from sklearn.cluster import KMeans
from sklearn import metrics
wine = pd.read_csv("winequality-red.csv",sep=";")
print(wine)
x = wine.drop("quality",axis=1)
y = wine["quality"].values
model = KMeans(n_clusters=4).fit(x)
#model.fit(x,y)
print(model)
kq = model.predict(x)
print(kq)
print(metrics.confusion_matrix(y,kq))
# kmean theo cum
